# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# SEO settings
title: Logopädische Praxis Manuela Dörfel | Heidenau

description: >
  Logopädische Praxis in zentraler Lage in Heidenau, Sachsen. Atem-, Sprach-, Sprech-, Stimm-, Hör- und Schluckthereapie für alle Altersgruppen. Alle Kassen.
  
baseurl: ""
url: "heidenau-logopaedie.de"
logo: logo.svg
logo-light: logo-light.svg

image: heidenau-logopaedie.jpg


#Contact Information
email: logopaedie-doerfel@gmx.de
phone: 03529 / 52 90 216
fax: 03529 / 52 90 217
# mobile: 0173 / 61 52 754

address:  'Ernst-Thälmann-Straße 7<br>
          01809 Heidenau'


# Social Media
facebook: ""
twitter: ""
google: ""


# Build settings
markdown: kramdown

include: ['_pages']